# Generated by Django 4.2.7 on 2023-12-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_about_date_time"),
    ]

    operations = [
        migrations.RenameField(model_name="about", old_name="name", new_name="u_name",),
    ]
