# Generated by Django 4.2.7 on 2024-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_about_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="email",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
