# Generated by Django 4.2.7 on 2024-02-06 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("district", "0001_initial"),
        ("division", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                (
                    "dis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="district.districts",
                    ),
                ),
                (
                    "div_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="division.divisions",
                    ),
                ),
            ],
        ),
    ]
